version: '3'
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        container_name: mysql57_instance
        command: mysqld  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: hZrXKMWYZ5tkSCgt
            MYSQL_USER: b2e_user
            MYSQL_PASSWORD: 0ioaN3QpZr8ugXtk
    b2e:
        build: .
        depends_on:
            - mysql
        # restart: always
        # command: python3 manage.py runserver 0.0.0.0:8000
        command: uwsgi --ini /var/www/b2e/default_uwsgi.ini
        ports:
            - "8000:8000"
            - "8001:8001"
            - "80:80"
        container_name: b2e_instance
        volumes:
            - .:/var/www/b2e
        links:
            - mysql:mysql57
